/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.src.test.java.src;

import org.junit.jupiter.api.Test;

import app.src.main.java.src.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
